#!/usr/bin/python3

from typing import List

import json
import sys


with open(".git/hooks/data.json") as f:
    data = json.load(f)

commit_msg_filepath = sys.argv[1]

emojis = [*data.values()]
prefixes = [*data.keys()]


def get_emoji_from_prefix(prefix: str):
    """-----------------------------------------------------------------------------
    Extracts emoji from elojis dict.
    -----------------------------------------------------------------------------"""
    try:
        return data[prefix]
    except KeyError as e:
        print(f"Unknown prefix: {prefix}")
        sys.exit(1)


def parse_prefixes(prefixes: str) -> List[str]:
    """-----------------------------------------------------------------------------
    Converts prefixes in string format into list of strings.
    -----------------------------------------------------------------------------"""
    return [p.strip().lower() for p in prefixes.split("+")]


with open(commit_msg_filepath, "r+") as f:
    c = f.read()

    try:
        prefixes, *content = c.split(":")
    except IndexError:
        print(
            "The commit message must follow the following format: [prefixes]: [message]"
        )
        sys.exit(1)

    if len(prefixes.split(" ")) == 2:
        sys.exit(0)

    parsed_prefixes = parse_prefixes(prefixes)

    parsed_emojis = [
        get_emoji_from_prefix(parsed_prefix) for parsed_prefix in parsed_prefixes
    ]

    msg_prefixes = "+".join(parsed_prefixes)
    msg_emojis = "+".join(parsed_emojis)
    msg_content = ":".join(content)

    f.seek(0, 0)
    f.write(f"{msg_emojis} {msg_prefixes}: {msg_content}".strip())
